apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luxe-jewelry-app
spec:
  source:
    repoURL: https://github.com/nofar-int/Luxe-Jewelry-Store-K8s.git
    path: infra/k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec
    - group: keda.sh
      kind: ScaledObject
      jsonPointers:
        - /spec




