apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: luxe-jewelry-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nofar-int/Luxe-Jewelry-Store-K8s.git
    path: infra/k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
      - SkipSchemaValidation=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: auth-deployment
      jsonPointers:
        - /spec
    - group: apps
      kind: Deployment
      name: backend-deployment
      jsonPointers:
        - /spec
    - group: apps
      kind: Deployment
      name: frontend-deployment
      jsonPointers:
        - /spec


