apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: auth-scaledobject
  namespace: demo-app
spec:
  scaleTargetRef:
    name: auth-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
