apiVersion: v1
kind: Service
metadata:
  name: jewelry-store-service
  namespace: demo-app
spec:
  selector:
    app: jewelry-store
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
